# Generated by Django 4.1.2 on 2022-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date_time', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('name_of_invoicer', models.CharField(max_length=100)),
                ('payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date_time', models.DateTimeField(auto_now_add=True)),
                ('buying_date', models.DateTimeField()),
                ('name_of_article', models.CharField(max_length=100)),
                ('name_of_store', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('days_of_warranty', models.PositiveBigIntegerField(default=365)),
            ],
        ),
    ]
